import { NextResponse } from 'next/server';
import dbConnect from '@/lib/mongodb';
import { LectureReport } from '@/models/Schemas';
import { GoogleGenerativeAI } from '@google/generative-ai';
import ffmpeg from 'fluent-ffmpeg';
import ffmpegInstaller from '@ffmpeg-installer/ffmpeg';
import axios from 'axios';
import fs from 'fs';
import path from 'path';
import os from 'os';

// Setup ffmpeg
ffmpeg.setFfmpegPath(ffmpegInstaller.path);

const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY || "");

export async function POST(req: Request) {
    const startTime = Date.now();
    let tempVideoPath = "";
    let tempAudioPath = "";
    
    try {
        await dbConnect();
        const { reportId } = await req.json();

        console.log(`[AI ANALYSIS] Starting analysis for Report: ${reportId}`);

        if (!reportId) {
            return NextResponse.json({ error: "Report ID is required" }, { status: 400 });
        }

        const report = await LectureReport.findById(reportId);
        if (!report) {
            console.error(`[AI ANALYSIS] Report not found: ${reportId}`);
            return NextResponse.json({ error: "Report not found" }, { status: 404 });
        }

        if (!report.recordingUrl) {
            console.error(`[AI ANALYSIS] No recording URL for report: ${reportId}`);
            return NextResponse.json({ error: "No recording URL found for this lecture" }, { status: 400 });
        }

        const recordingUrl = report.recordingUrl;
        tempVideoPath = path.join(os.tmpdir(), `video_${reportId}_${Date.now()}.mp4`);
        tempAudioPath = path.join(os.tmpdir(), `audio_${reportId}_${Date.now()}.mp3`);

        console.log(`[AI ANALYSIS] Step 1: Downloading from Cloudinary...`);
        try {
            const response = await axios({
                url: recordingUrl,
                method: 'GET',
                responseType: 'stream'
            });

            const writer = fs.createWriteStream(tempVideoPath);
            response.data.pipe(writer);

            await new Promise((resolve, reject) => {
                writer.on('finish', resolve);
                writer.on('error', (err) => {
                    console.error("[AI ANALYSIS] Download stream error:", err);
                    reject(err);
                });
            });
            console.log(`[AI ANALYSIS] Download complete: ${tempVideoPath}`);
        } catch (dlErr: any) {
            console.error("[AI ANALYSIS] Download Failed:", dlErr.message);
            throw new Error(`Failed to download recording: ${dlErr.message}`);
        }

        console.log(`[AI ANALYSIS] Step 2: Extracting Audio via FFMPEG...`);
        try {
            await new Promise((resolve, reject) => {
                ffmpeg(tempVideoPath)
                    .toFormat('mp3')
                    .on('start', (cmd) => console.log("[AI ANALYSIS] FFmpeg started"))
                    .on('end', () => {
                        console.log("[AI ANALYSIS] FFmpeg extraction finished");
                        resolve(true);
                    })
                    .on('error', (err) => {
                        console.error("[AI ANALYSIS] FFmpeg Error:", err);
                        reject(err);
                    })
                    .save(tempAudioPath);
            });
        } catch (ffErr: any) {
            console.error("[AI ANALYSIS] FFmpeg Failed:", ffErr.message);
            throw new Error(`Audio extraction failed. This usually happens with large files or corrupt streams. ${ffErr.message}`);
        }

        if (!fs.existsSync(tempAudioPath)) {
            throw new Error("Audio file was not generated by FFmpeg");
        }

        const audioSize = fs.statSync(tempAudioPath).size;
        console.log(`[AI ANALYSIS] Step 3: Preparing Gemini Phase 1 (Transcription). Audio Size: ${(audioSize / 1024 / 1024).toFixed(2)} MB`);
        
        const audioData = fs.readFileSync(tempAudioPath);
        const base64Audio = audioData.toString('base64');

        const modelPro = genAI.getGenerativeModel({ 
            model: "gemini-1.5-pro",
        });
        
        const transcriptionPrompt = `Transcribe this lecture audio accurately and COMPLETELY. 
        It is CRITICAL that the transcription covers the ENTIRE duration of the audio file.
        Include timestamps in [MM:SS] format at the beginning of each logical segment or every 30 seconds.
        If there are periods of silence, mark them as [Silence] with the corresponding timestamp.
        The content might be in Hindi, English, or Hinglish (mix of both). Transcribe it exactly as spoken.
        Format the output as a continuous stream of text segments with timestamps.`;

        console.log("[AI ANALYSIS] Dispatching Transcription Request...");
        const transcriptionResult = await modelPro.generateContent([
            {
                inlineData: {
                    data: base64Audio,
                    mimeType: "audio/mp3"
                }
            },
            { text: transcriptionPrompt }
        ]);

        const transcriptionText = transcriptionResult.response.text();
        console.log(`[AI ANALYSIS] Phase 1 Complete. Transcription Length: ${transcriptionText.length}`);

        console.log("[AI ANALYSIS] Step 4: Starting Phase 2 (Pedagogical Analysis)...");
        const analysisPrompt = `Analyze the following lecture transcript and provide a comprehensive pedagogical report in JSON format.
        Use easy English vocabulary so the report is simple to understand for everyone.
        
        Transcript:
        ${transcriptionText}
        
        REQUIRED JSON STRUCTURE:
        {
          "score": number (0-100),
          "summary": "overall session summary",
          "sections": [{ "title": "string", "startTime": "MM:SS", "endTime": "MM:SS", "summary": "string", "keyTakeaways": ["string"] }],
          "sentenceImprovements": [{ "original": "string", "improved": "string", "reason": "string", "timestamp": "MM:SS" }],
          "gapAnalysis": { "missingConcepts": ["string"] },
          "suggestions": ["string"],
          "flags": [{ "type": "warning|info|error", "message": "string", "timestamp": "MM:SS" }]
        }`;

        // Force JSON response mode for Phase 2
        const analysisModel = genAI.getGenerativeModel({ 
            model: "gemini-1.5-pro",
            generationConfig: { responseMimeType: "application/json" }
        });

        const analysisResult = await analysisModel.generateContent(analysisPrompt);
        const analysisResponseText = analysisResult.response.text();
        
        console.log("[AI ANALYSIS] Phase 2 JSON received. Parsing...");
        let analysis;
        try {
            analysis = JSON.parse(analysisResponseText);
        } catch (jsonErr) {
            console.error("[AI ANALYSIS] JSON Parsing Error. Raw Text:", analysisResponseText);
            // Fallback: try to extract JSON with regex if model ignored the setting
            const jsonMatch = analysisResponseText.match(/\{[\s\S]*\}/);
            if (jsonMatch) {
                analysis = JSON.parse(jsonMatch[0]);
            } else {
                throw new Error("Failed to parse pedagogical analysis JSON");
            }
        }

        console.log("[AI ANALYSIS] Updating database...");
        report.pedagogicalAnalysis = analysis;
        report.isAIProcessed = true;
        report.aiAnalysisAt = new Date().toISOString();
        report.transcription = transcriptionText;
        await report.save();

        console.log(`[AI ANALYSIS] SUCCESS. Total duration: ${((Date.now() - startTime) / 1000).toFixed(1)}s`);

        return NextResponse.json({ success: true, analysis });
    } catch (error: any) {
        console.error("[AI ANALYSIS] FATAL ERROR:", error);
        return NextResponse.json({ 
            success: false, 
            error: error.message || "An unexpected error occurred during AI analysis",
            stage: "server_crash" 
        }, { status: 500 });
    } finally {
        // ALWAYS cleanup temp files
        try {
            if (tempVideoPath && fs.existsSync(tempVideoPath)) fs.unlinkSync(tempVideoPath);
            if (tempAudioPath && fs.existsSync(tempAudioPath)) fs.unlinkSync(tempAudioPath);
            console.log("[AI ANALYSIS] Temp files cleaned.");
        } catch (e) {
            console.error("[AI ANALYSIS] Cleanup Warning:", e);
        }
    }
}
